'use client'

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 phantoms.glb -t 
Author: GreenG (https://sketchfab.com/AngelNebesniy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-from-the-series-love-death-and-robots-3c2c43c8737341e5816c61634782373a
Title: Robot from the series "Love death and robots"
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type ActionName = 'Scene'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Object_10: THREE.SkinnedMesh
    _rootJoint: THREE.Bone
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Robot(props: any) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF('./models/robot/phantoms.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="13b38b2398744f4295b469a8c9d906d1fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Empty" position={[2.458, 0, -102.215]} rotation={[0, 0, Math.PI / 2]} />
                <group name="Kosti" position={[13.777, 460.07, -5.148]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_9" />
                    <skinnedMesh
                      name="Object_10"
                      geometry={(nodes.Object_10 as THREE.SkinnedMesh).geometry}
                      material={materials.Material}
                      skeleton={(nodes.Object_10 as THREE.SkinnedMesh).skeleton}
                    />
                  </group>
                </group>
                <group name="Empty001" position={[13.138, 0.369, 88.479]} rotation={[0, 0, -Math.PI / 2]} />
                <group name="1_L" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/robot/phantoms.glb')
